### ISSUE TITLE
[Enhancement] Make this work with the CommunityToolkit

### ISSUE THREAD

**Issue by dansiegel** [MindscapeHQ/Aspire.Hosting.Raygun#7]
# Description

While this works with the Raygun implementation of Ollama this does not currently work with the CommunityToolkit version of Ollama.

## Problem

Raygun OllamaResource provides a connection string like:

```cs
$"http://{Endpoint.Property(EndpointProperty.Host)}:{Endpoint.Property(EndpointProperty.Port)}"
```

Where the CommunityToolkit OllamaResource provides a connection string like:

```cs
$"Endpoint={PrimaryEndpoint.Property(EndpointProperty.Scheme)}://{PrimaryEndpoint.Property(EndpointProperty.Host)}:{PrimaryEndpoint.Property(EndpointProperty.Port)}"
```

This results in an error where the connection string may be improperly formatted which results in an error starting the Raygun Host:

```bash
2024-11-17T19:38:07
 Unhandled exception. System.UriFormatException: Invalid URI: The URI scheme is not valid.
2024-11-17T19:38:07
    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
2024-11-17T19:38:07
    at System.Uri..ctor(String uriString)
2024-11-17T19:38:07
    at OllamaSharp.OllamaApiClient..ctor(String uriString, String defaultModel)
2024-11-17T19:38:07
    at RaygunAspireWebApp.Program.Main(String[] args) in /src/RaygunAspireWebApp/Program.cs:line 28
```

**Comment by QuantumNightmare** [comment]
Thanks dansiegel. We'll look into this as part of supporting the selected model in the connection string.
